// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtMVEAQvmmicRWzuPVWNGZQ_l9OXKHpZ0',
    appId: '1:43663105000:web:4799c50413ead472dca25d',
    messagingSenderId: '43663105000',
    projectId: 'recipe-app-2eeac',
    authDomain: 'recipe-app-2eeac.firebaseapp.com',
    storageBucket: 'recipe-app-2eeac.appspot.com',
    measurementId: 'G-VKCKYHC1TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QdTIvtomzUQtDSTn9p2hMzkBkme-FSI',
    appId: '1:43663105000:android:91dcede7d60ab758dca25d',
    messagingSenderId: '43663105000',
    projectId: 'recipe-app-2eeac',
    storageBucket: 'recipe-app-2eeac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUiyy6eIexqzooL9xYG-9tLT0z81zTnb8',
    appId: '1:43663105000:ios:92fce16a9ce74257dca25d',
    messagingSenderId: '43663105000',
    projectId: 'recipe-app-2eeac',
    storageBucket: 'recipe-app-2eeac.appspot.com',
    iosClientId: '43663105000-sf8265v6jhl15rf0ltnbrosj6vevtfgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUiyy6eIexqzooL9xYG-9tLT0z81zTnb8',
    appId: '1:43663105000:ios:92fce16a9ce74257dca25d',
    messagingSenderId: '43663105000',
    projectId: 'recipe-app-2eeac',
    storageBucket: 'recipe-app-2eeac.appspot.com',
    iosClientId: '43663105000-sf8265v6jhl15rf0ltnbrosj6vevtfgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp',
  );
}
