import 'dart:developer';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:recipes_app/Data/Ingredients.dart';
import 'package:recipes_app/Data/RecipeInformation.dart';
import 'package:recipes_app/models/Likedrecipe.dart';

import '../Data/Analyzedrecipe.dart';
import '../Data/cuisionRecipes.dart';

class RecipeHelper {
  RecipeHelper._();
  static RecipeHelper recipeHelper=RecipeHelper._();
  String apikey='a8653e1600b242a48c9416cd71815eb2';
  //List<Results>resultslist=[];
 
  Dio dio=Dio();
  Future<Autogenerated> getAllrecipes(String country)async{
   Response response= await dio.get("https://api.spoonacular.com/recipes/complexSearch?apiKey=$apikey&cuisine=$country");
    Autogenerated recipesData=Autogenerated.fromJson(response.data);

return recipesData;
    
  }

  Future<Autogenerated>getDiet(String diet)async{
   Response response= await dio.get("https://api.spoonacular.com/recipes/complexSearch?apiKey=$apikey&diet=$diet");
     Autogenerated recipesData=Autogenerated.fromJson(response.data);
return recipesData;
  }
   Future<Autogenerated>Search(String search)async{
   Response response= await dio.get("https://api.spoonacular.com/recipes/autocomplete?apiKey=$apikey&query=$search");
   log("----------------data: ${response.data}");
   List<dynamic> dataList = response.data;
     Autogenerated recipesData=Autogenerated.fromJson({"results":dataList});
     log("--------------results: "+recipesData.toString());
return recipesData;
  }
  Future<Autogenerateding> getRecipeIngredients(int id)async{
   
    Response response=await dio.get("https://api.spoonacular.com/recipes/$id/ingredientWidget.json?apiKey=$apikey&cuisine=italian");
    Autogenerateding ingredientData =Autogenerateding.fromJson(response.data);
    log(response.toString());
    return ingredientData;
   }
   Future<List<AutogeneratedAnalyzed>> getAnalyziedrecipe(int id)async{
    
    Response response=
    await dio.get("https://api.spoonacular.com/recipes/$id/analyzedInstructions?apiKey=$apikey");
     List analyzedmap=response.data;
     List<AutogeneratedAnalyzed>analyzedlist=analyzedmap.map((e) {
     return AutogeneratedAnalyzed.fromJson(e);
     
 
     }).toList();
     

    return analyzedlist ;
    
   }
   Future <List<Steps>>getSteps(int id)async{
      List<Steps>stepss=[];

  List<AutogeneratedAnalyzed>analyzedlist=await getAnalyziedrecipe(id);
  analyzedlist.map((e) {
     stepss=[];
 return stepss.addAll(e.steps??[]);
 

  }).toList();
  log("help");
log(stepss.length.toString());
  return stepss;
   }
  
 Future<Info>getInfo(int id)async{
  Response response=await dio.get("https://api.spoonacular.com/recipes/$id/information?apiKey=$apikey&includeNutrition=false");
Info recipeINformation= Info.fromJson(response.data??[]);
return recipeINformation;

 }
  
  Future<Autogenerateding> getLiked(int id)async{
   
    Response response=await dio.get("https://api.spoonacular.com/recipes/$id/ingredientWidget.json?apiKey=$apikey&cuisine=italian");
    Autogenerateding ingredientData =Autogenerateding.fromJson(response.data);
    log(response.toString());
    return ingredientData;
   }
   
}